query YELP($id: String!) {
  business(id: $id) {
    name
    id
    alias
    is_claimed
    is_closed
    url
    phone
    display_phone
    review_count
    categories {
      title
      alias
      parent_categories {
        title
        alias
      }
    }
    rating
    price
    location {
      address1
      address2
      address3
      city
      state
      postal_code
      country
      formatted_address
    }
    coordinates {
      latitude
      longitude
    }
    photos
    hours {
      hours_type
      open {
        is_overnight
        end
        start
        day
      }
      is_open_now
    }
    reviews {
      id
      rating
      user {
        id
        image_url
        profile_url
        name
      }
      text
      time_created
      url
    }
    distance
    attributes
    transactions {
      restaurant_reservations {
        url
      }
    }
  }
}
